apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-extensions-pv
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sonar-extensions"
  persistentVolumeReclaimPolicy: Retain

