# SonarQube Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      hostPID: true
      containers:
        - name: sonarqube
          image: sonarqube:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: SONARQUBE_JDBC_URL
              value: jdbc:postgresql://postgres.sonarqube.svc.cluster.local:5432/postgres
            - name: SONARQUBE_JDBC_USERNAME
              value: admin
            - name: SONARQUBE_JDBC_PASSWORD
              value: admin@123
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 2Gi
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /opt/sonarqube/data
              name: sonar-data
            - mountPath: /opt/sonarqube/extensions
              name: sonar-extensions
      volumes:
        - name: sonar-data
          persistentVolumeClaim:
            claimName: sonar-data-pvc
        - name: sonar-extensions
          persistentVolumeClaim:
            claimName: sonar-extensions-pvc
