# SonarQube PVCs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-data-pvc
  namespace: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-extensions-pvc
  namespace: sonarqube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi

