# SonarQube Service
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - port: 9000        # Port SonarQube listens on
      targetPort: 9000  # Container port
      nodePort: 30080   # Node port to access externally

                                                                                                                                                                                              214,0-1       Bot

