# SonarQube PersistentVolumes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-data-pv
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sonar-data"
  persistentVolumeReclaimPolicy: Retain

